spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/gestor_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  activemq:
    broker-url: tcp://localhost:6161
    user: admin
    password: admin

google:
  books:
    api:
      key: ${GOOGLE_BOOKS_API_KEY}
      url: https://www.googleapis.com/books/v1

logging:
  level:
    br.com.rzaninelli.gestor: DEBUG